The main thing is to do

    ipcluster start -n 4

In [1]:
import ipyparallel as ipp

In [2]:
c = ipp.Client()

In [3]:
c.ids

[0, 1, 2, 3]

In [4]:
c[:].apply_sync(lambda : "Hello, World")

['Hello, World', 'Hello, World', 'Hello, World', 'Hello, World']

In [10]:
dview = c[:]

In [11]:
# [x**2 for x in range(32)]
serial_result = list(map(lambda x:x**2, range(10)))

In [14]:
parallel_result = dview.map_sync(lambda x: x**2, range(10))

In [15]:
parallel_result

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [16]:
with dview.sync_imports():
    import numpy

importing numpy on engine(s)


In [23]:
def simple_f(i):
    return numpy.random.rand(i)

In [24]:
simple_f_result = dview.map_sync(simple_f, [1, 2, 3, 4, 5, 6, 7])

In [25]:
simple_f_result

[array([0.620793]),
 array([0.84590064, 0.39622357]),
 array([0.09270065, 0.43487385, 0.38044541]),
 array([0.14599238, 0.38283844, 0.20817362, 0.18327535]),
 array([0.53254393, 0.63706263, 0.89467206, 0.21413765, 0.16627571]),
 array([0.28341619, 0.45422304, 0.04264876, 0.57075148, 0.70744862,
        0.69716477]),
 array([0.97714128, 0.30863554, 0.81222306, 0.95062783, 0.76467227,
        0.41647623, 0.39445817])]

In [26]:
pwd

'/home/andrews/gitdev/misc/pspy01'

In [ ]:
8 * 