In [2]:
import numpy

In [3]:
x = numpy.random.rand(100, 10)
y = numpy.random.rand(10, 10, 10)

In [6]:
numpy.savetxt('rdata3d.txt', x,  delimiter=',', header = '12,3')

In [12]:
y = numpy.loadtxt('rdata3d.txt', delimiter=',', skiprows=1)

In [13]:
y

array([[7.26644142e-01, 3.88757468e-01, 5.25244610e-01, 4.47039794e-02,
        8.07846434e-01, 3.13053905e-01, 3.98643127e-01, 9.77255843e-01,
        6.53837213e-01, 2.06567586e-01],
       [8.61987483e-01, 4.66765434e-02, 4.58468216e-02, 9.39630878e-01,
        3.83423957e-01, 6.45543522e-01, 5.24058298e-01, 4.81013551e-01,
        8.98133199e-01, 6.29267768e-01],
       [3.56271126e-01, 6.45668682e-01, 2.91785697e-01, 2.89010147e-01,
        6.12196825e-01, 5.31133357e-02, 7.18622080e-01, 8.97215169e-02,
        1.86796974e-01, 6.46649208e-01],
       [1.04158588e-01, 4.18805151e-01, 2.37369613e-01, 1.92802910e-01,
        3.90263854e-01, 6.62933410e-01, 1.08891244e-01, 5.19555596e-01,
        9.15966517e-01, 5.59536219e-01],
       [4.93151578e-02, 8.04798916e-01, 2.29462806e-01, 8.32372723e-01,
        3.33700866e-01, 8.58914381e-01, 2.40525759e-01, 4.13484767e-01,
        9.30779906e-01, 4.80338447e-01],
       [8.37383129e-01, 3.15262243e-02, 9.80043059e-01, 1.17433004e-01,
   

In [ ]:
y = numpy.random.rand(10 * 10 * 10).reshape(10, 10, 10)

In [10]:
numpy.loadtxt

In [ ]:
z = numpy.load('foo.npy')

In [ ]:
(z == y).all()

In [40]:
?numpy.percentile

In [41]:
numpy.percentile(y, 99.9)

0.9994513098067329

In [42]:
?numpy.nanmin

In [45]:
x = numpy.random.rand(10).reshape((10, 1))

In [47]:
x + x

array([[1.02951938],
       [0.81803304],
       [0.16348859],
       [1.59741237],
       [1.13770633],
       [0.55136059],
       [0.17110413],
       [1.17151279],
       [1.77620796],
       [1.70320909]])

In [48]:
x

array([[0.51475969],
       [0.40901652],
       [0.0817443 ],
       [0.79870618],
       [0.56885316],
       [0.2756803 ],
       [0.08555206],
       [0.5857564 ],
       [0.88810398],
       [0.85160455]])

In [49]:
x

array([[0.51475969],
       [0.40901652],
       [0.0817443 ],
       [0.79870618],
       [0.56885316],
       [0.2756803 ],
       [0.08555206],
       [0.5857564 ],
       [0.88810398],
       [0.85160455]])

In [50]:
y = numpy.random.rand(10)

In [51]:
x + y

array([[0.89622346, 1.36989347, 1.36321269, 1.04015702, 0.77765166,
        0.6527356 , 0.63345623, 0.6752202 , 0.98827698, 0.54362999],
       [0.79048029, 1.2641503 , 1.25746952, 0.93441385, 0.67190849,
        0.54699243, 0.52771306, 0.56947703, 0.88253382, 0.43788682],
       [0.46320807, 0.93687808, 0.9301973 , 0.60714163, 0.34463627,
        0.21972021, 0.20044084, 0.24220481, 0.55526159, 0.11061459],
       [1.18016996, 1.65383997, 1.64715919, 1.32410352, 1.06159815,
        0.9366821 , 0.91740273, 0.9591667 , 1.27222348, 0.82757648],
       [0.95031694, 1.42398695, 1.41730617, 1.0942505 , 0.83174513,
        0.70682907, 0.68754971, 0.72931367, 1.04237046, 0.59772346],
       [0.65714407, 1.13081408, 1.1241333 , 0.80107763, 0.53857227,
        0.41365621, 0.39437684, 0.43614081, 0.74919759, 0.3045506 ],
       [0.46701584, 0.94068585, 0.93400507, 0.6109494 , 0.34844403,
        0.22352797, 0.20424861, 0.24601258, 0.55906936, 0.11442236],
       [0.96722017, 1.44089018, 1.4342094

In [53]:
(x * y).sum(axis = 0)

array([1.93012168, 4.32678636, 4.29298311, 2.65839341, 1.33017478,
       0.69812736, 0.60057805, 0.81189443, 2.39589198, 0.14607727])

In [56]:
x.transpose().dot(y)

array([1.77196865])

In [57]:
numpy.outer(x, y)

array([[0.19636217, 0.4401884 , 0.4367494 , 0.27045337, 0.13532619,
        0.07102444, 0.06110019, 0.0825986 , 0.24374761, 0.01486127],
       [0.15602499, 0.34976384, 0.3470313 , 0.21489619, 0.10752716,
        0.05643443, 0.04854885, 0.065631  , 0.1936764 , 0.01180843],
       [0.03118249, 0.06990231, 0.06935619, 0.04294824, 0.02148992,
        0.01127874, 0.00970277, 0.01311673, 0.03870734, 0.00235998],
       [0.30467747, 0.68300064, 0.67766466, 0.4196381 , 0.20997344,
        0.11020221, 0.09480366, 0.1281608 , 0.37820119, 0.02305889],
       [0.21699687, 0.48644556, 0.48264518, 0.29887393, 0.14954693,
        0.07848803, 0.0675209 , 0.09127847, 0.26936181, 0.01642296],
       [0.10516205, 0.23574354, 0.23390178, 0.14484169, 0.07247414,
        0.03803724, 0.0327223 , 0.0442358 , 0.13053939, 0.00795897],
       [0.03263501, 0.07315846, 0.07258691, 0.04494883, 0.02249095,
        0.01180412, 0.01015473, 0.01372773, 0.04051038, 0.00246991],
       [0.22344484, 0.50090008, 0.4969867

In [59]:
(x * y) == numpy.outer(x, y)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [65]:
y = numpy.random.rand(36)

In [67]:
y = y.reshape((6, 6))

In [68]:
y[0,1]

0.7913094459831597

In [82]:
y = numpy.array([[1, 2, 3], [4, 5, 6]], numpy.float64)

In [83]:
y.dtype

dtype('float64')

In [99]:
y[[0, 1, 0], 0] += 1.1

In [98]:
y

array([[5.3, 5.2, 3. ],
       [5.1, 5. , 9.2]])

In [104]:
y

array([[6.4, 5.2, 3. ],
       [6.2, 5. , 9.2]])

In [103]:
x  = x.transpose().flatten()

In [105]:
x

array([0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455])

In [112]:
numpy.corrcoef(x, numpy.random.random(x.shape))

array([[ 1.        , -0.36706876],
       [-0.36706876,  1.        ]])

In [114]:
x.ravel()

array([0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455])

In [116]:
?x.ravel

In [121]:
?x.resize

In [119]:
x

array([[0.51475969, 0.40901652],
       [0.0817443 , 0.79870618],
       [0.56885316, 0.2756803 ],
       [0.08555206, 0.5857564 ],
       [0.88810398, 0.85160455]])

In [125]:
x.flatten().reshape(2,5)

array([[0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316],
       [0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455]])

In [126]:
x

array([[0.51475969, 0.40901652],
       [0.0817443 , 0.79870618],
       [0.56885316, 0.2756803 ],
       [0.08555206, 0.5857564 ],
       [0.88810398, 0.85160455]])

In [127]:
x.ravel()

array([0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455])

In [128]:
x

array([[0.51475969, 0.40901652],
       [0.0817443 , 0.79870618],
       [0.56885316, 0.2756803 ],
       [0.08555206, 0.5857564 ],
       [0.88810398, 0.85160455]])

In [129]:
x.flatten()

array([0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455])

In [130]:
x

array([[0.51475969, 0.40901652],
       [0.0817443 , 0.79870618],
       [0.56885316, 0.2756803 ],
       [0.08555206, 0.5857564 ],
       [0.88810398, 0.85160455]])

In [131]:
x.resize(10)

In [137]:

numpy.hstack((x,x,x))

array([0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455,
       0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455,
       0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455])

In [140]:
numpy.r_[x,x]

array([0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455,
       0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316,
       0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455])

In [148]:
numpy.split(x, 2)

[array([0.51475969, 0.40901652, 0.0817443 , 0.79870618, 0.56885316]),
 array([0.2756803 , 0.08555206, 0.5857564 , 0.88810398, 0.85160455])]

In [153]:
?numpy.hsplit

In [154]:
 x = numpy.arange(16.0).reshape(4, 4)

In [155]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [161]:
numpy.vsplit(x,(4,2))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [163]:
y.T

array([[6.4, 6.2],
       [5.2, 5. ],
       [3. , 9.2]])

In [175]:
numpy.matrix("1. 2; 3 4; 5   6") * x

matrix([[ 5.],
        [11.],
        [17.]])

In [174]:
x = numpy.array([1, 2]).reshape(2,1)

In [178]:
eigen_val, eigen_vec = numpy.eig(y)

AttributeError: module 'numpy' has no attribute 'eig'

In [179]:
numpy.linalg.eig(y)

LinAlgError: Last 2 dimensions of the array must be square

In [187]:
y.T.reshape(3, 1, 2) - numpy.array([[10, 10], [10,10]])

array([[[-3.6, -3.8],
        [-3.6, -3.8]],

       [[-4.8, -5. ],
        [-4.8, -5. ]],

       [[-7. , -0.8],
        [-7. , -0.8]]])

In [185]:
Z = y.T.reshape(3, 1, 2)

In [190]:

Z - numpy.array([[10, 10], [-10,-10]])

array([[[-3.6, -3.8],
        [16.4, 16.2]],

       [[-4.8, -5. ],
        [15.2, 15. ]],

       [[-7. , -0.8],
        [13. , 19.2]]])

In [189]:
Z

array([[[6.4, 6.2]],

       [[5.2, 5. ]],

       [[3. , 9.2]]])